# Generated by Django 4.1.1 on 2023-02-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djwebdapp_tezos", "0004_delete_tezoscall_delete_tezoscontract"),
    ]

    operations = [
        migrations.CreateModel(
            name="TezosCall",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("djwebdapp_tezos.tezostransaction",),
        ),
        migrations.CreateModel(
            name="TezosContract",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("djwebdapp_tezos.tezostransaction",),
        ),
    ]
