image: yourlabs/python

build:
  image: docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script: pip install .[test,vault] && py.test -sv tests

tezos:
  stage: test
  script: pip install .[all] && py.test -sv src/djwebdapp_tezos*
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
  - alias: tzkt-db
    name: postgres:13
    variables:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db
  - alias: tzkt-api
    name: bakingbad/tzkt-api:latest
    variables:
      TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://tzkt-api:5000
      TezosNode__Endpoint: http://tzlocal:8732
  - alias: sync
    name: bakingbad/tzkt-sync:latest
    variables:
      TezosNode__Endpoint: http://tzlocal:8732
  - alias: tzlocal
    name: yourlabs/tezos

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]
