image: yourlabs/python

build:
  image: docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

tzkt-api-build:
  image: docker:dind
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f src/djwebdapp_tezos_example/Dockerfile.tzkt-api -t $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}-tzkt-api .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}-tzkt-api

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script: pip install .[test,vault] && py.test -sv tests

tezos:
  stage: test
  script: pip install .[all] && py.test -sv src/djwebdapp_tezos*
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  variables:
    POSTGRES_USER: tzkt
    POSTGRES_PASSWORD: qwerty
    POSTGRES_DB: tzkt_db
    TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://tzkt-api:5000
    TezosNode__Endpoint: http://tzlocal:8732
    ConnectionStrings__DefaultConnection: host=tzkt-db;port=5432;database=tzkt_db;username=tzkt;password=qwerty;

  services:
  - alias: tzkt-db
    name: postgres:13
  - alias: tzkt-api
    name: $CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}-tzkt-api
  - alias: sync
    name: bakingbad/tzkt-sync:latest
  - alias: tzlocal
    name: yourlabs/tezos

pypi:
  stage: deploy
  script: pypi-release
  only: [tags]
