version: '3'

services:
  ethlocal:
    container_name: ethlocal
    volumes:
    - /root
    image: ethereum/client-go
    command: --dev --networkid=17 --nodiscover --maxpeers=0 --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.vhosts "*" --http.api "eth,net,web3,personal,miner" --miner.gasprice 0 --ws --ws.addr 0.0.0.0 --nousb --gcmode archive --datadir=/root/.ethereum
    ports:
    - 0.0.0.0:8545:8545
    - 0.0.0.0:8546:8546
    - 0.0.0.0:30303:30303

  tzlocal:
    container_name: tzlocal
    image: yourlabs/tezos
    ports:
      - 0.0.0.0:8732:8732

  db:
    container_name: tzkt-db
    image: postgres:13
    environment:
      POSTGRES_USER: tzkt
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: tzkt_db

  api:
    container_name: tzkt-api
    image: bakingbad/tzkt-api:latest
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: host=tzkt-db;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
      TZKT_API_KESTREL__ENDPOINTS__HTTP__URL: http://0.0.0.0:5000
      TezosNode__Endpoint: http://tzlocal:8732
    expose:
      - 5000
    ports:
      - 0.0.0.0:5000:5000

  sync:
    container_name: tzkt-sync
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=tzkt-db;port=5432;database=tzkt_db;username=tzkt;password=qwerty;
      TezosNode__Endpoint: http://tzlocal:8732
    depends_on:
      - db
