# Generated by Django 4.2.2 on 2023-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djwebdapp_ethereum', '0003_ethereumtransaction_caller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtransaction',
            name='_receipt',
            field=models.JSONField(blank=True, default=dict, help_text='Transaction receipt', null=True),
        ),
    ]
