# Generated by Django 4.1.1 on 2023-01-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("djwebdapp", "0013_transaction_normalized"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionGraph",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionEdge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djwebdapp_txgraph.transactiongraph",
                    ),
                ),
                (
                    "input_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactiongraphinput_set",
                        to="djwebdapp.transaction",
                    ),
                ),
                (
                    "output_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactiongraphoutput_set",
                        to="djwebdapp.transaction",
                    ),
                ),
            ],
        ),
    ]
