# Generated by Django 3.2.18 on 2023-04-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djwebdapp', '0015_alter_transaction_state'),
        ('djwebdapp_ethereum', '0003_ethereumtransaction_caller'),
    ]

    operations = [
        migrations.CreateModel(
            name='FA12Ethereum',
            fields=[
                ('ethereumtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djwebdapp_ethereum.ethereumtransaction')),
                ('token_name', models.CharField(max_length=200)),
                ('token_symbol', models.CharField(max_length=10)),
            ],
            bases=('djwebdapp_ethereum.ethereumcontract',),
        ),
        migrations.CreateModel(
            name='FA12EthereumMint',
            fields=[
                ('ethereumtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djwebdapp_ethereum.ethereumtransaction')),
                ('mint_amount', models.PositiveIntegerField()),
                ('mint_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djwebdapp.account')),
                ('target_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djwebdapp_example_ethereum.fa12ethereum')),
            ],
            bases=('djwebdapp_ethereum.ethereumcall',),
        ),
        migrations.CreateModel(
            name='FA12EthereumBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djwebdapp.account')),
                ('fa12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djwebdapp_example_ethereum.fa12ethereum')),
            ],
            options={
                'unique_together': {('fa12', 'account')},
            },
        ),
    ]
