# Generated by Django 4.1 on 2022-09-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djwebdapp", "0007_alter_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="txgroup",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
