# Generated by Django 4.1a1 on 2022-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djwebdapp", "0012_transaction_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="dependencies",
            field=models.ManyToManyField(
                default=list, related_name="consumer_set", to="djwebdapp.transaction"
            ),
        ),
    ]
