# Generated by Django 4.1.1 on 2023-01-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djwebdapp", "0012_transaction_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="normalized",
            field=models.BooleanField(
                default=False, help_text="Enabled when transaction is normalized"
            ),
        ),
    ]
