# Generated by Django 3.2.18 on 2023-04-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djwebdapp', '0017_create_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='level',
        ),
    ]
