# Generated by Django 5.2 on 2026-01-13 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djwebdapp", "0020_alter_account_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexedBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(db_index=True)),
                ("block_hash", models.CharField(max_length=66)),
                (
                    "blockchain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djwebdapp.blockchain",
                    ),
                ),
            ],
            options={
                "unique_together": {("blockchain", "level")},
            },
        ),
    ]
